### ISSUE TITLE
Multiple hrefs

### ISSUE THREAD

**Issue by keul** [threepointone/css-suspense#3]
I'm wondering if you ever evaluated having `href` prop optionally as an array of CSS (or adding a new prop), for load multiple resources in a concurrent way.

Right now this is possible by nesting `Stylesheet`, but it's verbose and this will not load CSSes concurrently.

**Comment by threepointone** [comment]
You can have multiple tags as siblings and that should do the trick? They all suspend together, so you should get the concurrent behaviour you need

**Comment by keul** [comment]
Sorry, you are right, that's "the suspence way" I think!
