### ISSUE TITLE
Behavior in case of error loading CSS

### ISSUE THREAD

**Issue by keul** [threepointone/css-suspense#4]
I've my application broken in case the specified CSS at `href` is not found.

The fact is that the components returns a failing promises in this case. I can easily wrap this into an error boundary, but I think the component itself should react easily in case of errors (maybe adding an onError props?).

Also: it should not try to add the `link` tag in case of error, while right it seems to be added in any case.

**Comment by threepointone** [comment]
I think the error boundary is the right way to do it.
